name: "CONFIG COLLECTOR"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
                
    - name: Execute script  
      run: |
        bash ./grab.sh
        git config --global user.email "ronaldjc63@gmail.com"
        git config --global user.name "rony432"
        git config credential.helper store
        git add -A
        git commit -m "🚀 Servers Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
        git push
